<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>Verify deskripsi modul bima</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>android.view.View</value>
      <webElementGuid>9227251d-b6fc-47db-9bf4-127a0b58c4ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2708d8c6-d716-401e-baa6-302cee08ea56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>package</name>
      <type>Main</type>
      <value>id.satudikti.app</value>
      <webElementGuid>2b70061d-38f4-44fb-8aa7-591e13fb769a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>content-desc</name>
      <type>Main</type>
      <value>BIMA (Basis Informasi Penelitian dan Pengabdian kepada Masyarakat) merupakan sebuah layanan untuk mengajukan usulan penelitian maupun pengabdian, hingga melaporkan kegiatan yang bisa dilakukan secara online melalui website. BIMA bertujuan untuk mengelola program penelitian dan pengabdian, serta proses pemberian hibah kepada masyarakat di perguruan tinggi di bawah Direktorat Jenderal Pendidikan Tinggi, Riset, dan Teknologi. BIMA dikembangkan untuk menggantikan layanan SIMLITABMAS yang sebelumnya diluncurkan oleh Ditjen Dikti. 

Lahirnya suatu karya penelitian secara tidak langsung akan berpengaruh terhadap kemampuan berpikir dan menulis bagi para pembacanya sekaligus menjadi solusi atas permasalahan yang timbul di masyarakat, daerah, nasional hingga global. Selain itu, pengabdian terhadap masyarakat juga menjadi hal yang penting dalam dunia pendidikan tinggi. Hal tersebut memiliki pengaruh dan manfaat yang besar terhadap tingkat kepedulian pada lingkungan sosial.</value>
      <webElementGuid>eec4cdd6-6fda-4bd0-a7f1-e115327b126d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checkable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c3b48169-fb7b-4f07-8ea2-924d8897303b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e0b534f9-591a-4634-9472-3ec322843c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c152f697-f715-40a6-b726-76d1a96acda6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>91809127-e7e0-46df-90d0-67d5c5f3571f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>36e1a200-557d-44ab-abed-d50be2f5fbb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focused</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c6f971c9-8c9e-4bd6-9876-4100fac8141e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrollable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>eb85361a-90b9-443a-835c-486ac515e7e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>long-clickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bd616829-1b22-466e-8b73-08edee7964da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>password</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>25facc00-181d-4e3f-ad92-b9539a9fa9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9c344519-7b54-4c5f-86ff-54aa54586413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>65a0ee72-ad7b-4740-a7f3-07db3a2149ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>983</value>
      <webElementGuid>74587808-adc7-4972-951a-a41df0186fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>982</value>
      <webElementGuid>92c1880f-453f-4ba3-adc1-e6dbb100f116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>854</value>
      <webElementGuid>6d40d3ce-8c8b-4b48-8ba1-8af187a80528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bounds</name>
      <type>Main</type>
      <value>[48,983][1030,1837]</value>
      <webElementGuid>ce0009ad-3f6e-45d7-9181-0b82802ab176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5089f247-8252-40cf-9a9b-4cf0dd02acf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>resource-id</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>1c53a7c0-a54e-4f6e-ba73-4cddaedfca26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>f49db726-4cf6-446d-b625-648fcdf67015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//hierarchy/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.widget.ScrollView[1]/android.view.View[1]</value>
      <webElementGuid>a7458154-9b8f-42cc-a70b-0b87adad5b64</webElementGuid>
   </webElementProperties>
   <locator>BIMA (Basis Informasi Penelitian dan Pengabdian kepada Masyarakat) merupakan sebuah layanan untuk mengajukan usulan penelitian maupun pengabdian, hingga melaporkan kegiatan yang bisa dilakukan secara online melalui website. BIMA bertujuan untuk mengelola program penelitian dan pengabdian, serta proses pemberian hibah kepada masyarakat di perguruan tinggi di bawah Direktorat Jenderal Pendidikan Tinggi, Riset, dan Teknologi. BIMA dikembangkan untuk menggantikan layanan SIMLITABMAS yang sebelumnya diluncurkan oleh Ditjen Dikti. 

Lahirnya suatu karya penelitian secara tidak langsung akan berpengaruh terhadap kemampuan berpikir dan menulis bagi para pembacanya sekaligus menjadi solusi atas permasalahan yang timbul di masyarakat, daerah, nasional hingga global. Selain itu, pengabdian terhadap masyarakat juga menjadi hal yang penting dalam dunia pendidikan tinggi. Hal tersebut memiliki pengaruh dan manfaat yang besar terhadap tingkat kepedulian pada lingkungan sosial.</locator>
   <locatorStrategy>ACCESSIBILITY</locatorStrategy>
</MobileElementEntity>
